import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'; // Import your Footer component
import Navigation from './components/new-landing/Navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ecompasse Digital Solutions',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./assets/favicon.png"/>
      </head>
      <body className={inter.className}>
        <Navigation /> {/* Render your Header component */}
        {children} {/* Render the content */}
        <Footer /> {/* Render your Footer component */}
      </body>
    </html>
  )
}
